#! /bin/sh

bspc config border_width        1
bspc config window_gap         20

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true
bspc config auto_cancel         true
bspc config initial_polarity    second_child


bspc monitor LVDS-1 -d I II III IV
bspc monitor VGA-1 -d VIII IX X
bspc monitor HDMI-0 -d V VI VII

bspc rule -a Firefox desktop=^2
bspc rule -a Telegram desktop=^1
bspc rule -a mpv desktop=^5

telegram&
firefox&

dunst&
panel&
